name: security_scan

on: [push]

jobs:
  workflow:
    runs-on: [ubuntu-latest,linux-latest]
    name: "make"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run Make
        run: make 